name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    # Add explicit permissions
    permissions:
      contents: write # For creating releases
      issues: write # For creating issues
      pull-requests: write # For creating PRs
      packages: write # For publishing packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build library
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook
        env:
          NODE_ENV: production

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
